[package]
name = "rustnoise"
version = "0.1.0"
authors = ["felix-lipski <felix.lipski7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.7.0"
plotters = "0.3.0"
plotters-backend = "0.3.0"
